hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
hibernate.connection.url=jdbc:mysql://localhost:3306/hibernatedb
hibernate.connection.username=root
hibernate.connection.password=rvr@csd
hibernate.hbm2ddl.auto=update
hibernate.show_sql=true
hibernate.format_sql=true